
spring:
  application:
    name: chatter
  flyway:
    user: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    schemas: "${DB_SCHEMA}"
    url: "${DB_URL}"
  datasource:
    url: "${DB_URL}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}"
